In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\HP\Downloads\StudentPerformanceFactors.csv")

In [4]:
df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [5]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [6]:
df.rename(columns={'Access_to_Resources':'Resources','Extracurricular_Activities':'Extracurricular','Parental_Education_Level':'Parent Education'},inplace=True)
df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Resources,Extracurricular,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parent Education,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [7]:
df.isnull().sum()

Hours_Studied             0
Attendance                0
Parental_Involvement      0
Resources                 0
Extracurricular           0
Sleep_Hours               0
Previous_Scores           0
Motivation_Level          0
Internet_Access           0
Tutoring_Sessions         0
Family_Income             0
Teacher_Quality          78
School_Type               0
Peer_Influence            0
Physical_Activity         0
Learning_Disabilities     0
Parent Education         90
Distance_from_Home       67
Gender                    0
Exam_Score                0
dtype: int64

In [8]:
df[['Teacher_Quality','Parent Education','Distance_from_Home']].isnull().mean()*100

Teacher_Quality       1.180566
Parent Education      1.362192
Distance_from_Home    1.014076
dtype: float64

In [11]:
cols=['Teacher_Quality','Parent Education','Distance_from_Home']
for i in cols:
    df[i]=df[i].fillna(df[i].mode()[0])

In [12]:
df.isnull().sum()

Hours_Studied            0
Attendance               0
Parental_Involvement     0
Resources                0
Extracurricular          0
Sleep_Hours              0
Previous_Scores          0
Motivation_Level         0
Internet_Access          0
Tutoring_Sessions        0
Family_Income            0
Teacher_Quality          0
School_Type              0
Peer_Influence           0
Physical_Activity        0
Learning_Disabilities    0
Parent Education         0
Distance_from_Home       0
Gender                   0
Exam_Score               0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df=df.drop_duplicates()

In [16]:
df.duplicated().sum()

np.int64(0)